#!/bin/bash
#SBATCH --time=12:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=2048M   # memory per CPU core
#SBATCH -J "VisionFilter"   # job name
module unload matlab
module load matlab/r2017b
matlab -r "main($1)"
